name: 'INSTALL:DEPENDENCIES'
description: 'Install Dependencies for Running Jobs'
inputs:
  github_token:
    description: "github token to use to call the api"
    required: true
  cpu_architecture:
    description: "CPU architecture"
    required: false
    default: "amd64"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'

    - shell: bash
      env:         
        CPU_ARCH: ${{ inputs.cpu_architecture }}
      run: |
        echo $cpu_architecture
        echo ${{ github.event.inputs.CPU_ARCHITECTURE }}

    - shell: bash
      if:  ${{ inputs.cpu_architecture == 'arm64' }}
      run: |
        echo "IS ARM CPU"
        echo ${{ github.event.inputs.cpu_architecture }}

    - uses: actions/setup-python@v4
      if: ${{ inputs.cpu_architecture == 'amd64' }}
      with:
        python-version: 'pypy3.9'

    - uses: chrisdickinson/setup-yq@latest

    # - id: install-aws-cli
    #   uses: unfor19/install-aws-cli-action@v1
    #   with:
    #     version: 2
    #     arch: "amd64" # ${{ github.event.inputs.cpu_architecture }}

    # - name: install-aws-cli
    #   shell: bash
    #   run: |
    #     curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
    #     chmod +x install-aws.sh
    #     ./install-aws.sh "v2" "$INPUT_CPU_ARCHITECTURE"
    #     rm install-aws.sh  

    - name: Dependencies.
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install wget jq -y

    - name: Install Docker Compose
      shell: bash
      run: |

        sudo apt-get update || echo "Issue running apt-get update."
        sudo apt-get install \
          ca-certificates \
          curl \
          gnupg \
          lsb-release -y || echo "issue installing dependencies"
        sudo mkdir -p /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --no-tty --batch --dearmor --yes -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update || echo "Issue running apt-get update."
        sudo apt-get install docker-compose-plugin -y || echo "Issue installing docker compose"

