name: 'INSTALL:DEPENDENCIES'
description: 'Install Dependencies for Running Jobs'
inputs:
  github_token:
    description: "github token to use to call the api"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'

    - uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'

    - uses: chrisdickinson/setup-yq@latest

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2

    - name: Dependencies.
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install wget jq -y

