version: '3.8'
services:
  zetachain_mainnet_rpc:
    platform: linux/amd64
    #This will build the binary from the GIT_REF you are locally on.
#    build:
#      context: ../..
#      dockerfile: Dockerfile
    #If you want to use the pre-built docker images you would comment out Build lines, and uncomment this line with the correct docker tag.
    #image: zetachain/zeatcored:ubuntu-{CURRENT_RELEASE_VERSION}
    image: local/zetacored:v0.2.8
    container_name: zetachain_mainnet_rpc
    environment:
      DAEMON_HOME: "/root/.zetacored"
      NETWORK: mainnet
      #RESTORE_TYPE=snapshot/snapshot-archive/statesync
      RESTORE_TYPE: "statesync"
      SNAPSHOT_API: https://snapshots.zetachain.com
      #for statesync needs to be set
      #TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: 40000
      TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: 100
      COSMOVISOR_VERSION: "v1.5.0"
      CHAIN_ID: "zetachain_7000-1"
      COSMOVISOR_CHECKSUM: "626dfc58c266b85f84a7ed8e2fe0e2346c15be98cfb9f9b88576ba899ed78cdc"
      VISOR_NAME: "cosmovisor"
      DAEMON_NAME: "zetacored"
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "false"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
      UNSAFE_SKIP_BACKUP: "true"
      CLIENT_DAEMON_NAME: "zetaclientd"
      CLIENT_DAEMON_ARGS: ""
      CLIENT_SKIP_UPGRADE: "true"
      CLIENT_START_PROCESS: "false"
      MONIKER: local-test
      RE_DO_START_SEQUENCE: false
    ports:
      - "26656:26656"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - zetacored_data:/root/.zetacored/
    entrypoint: bash /scripts/start.sh
    #entrypoint: ["/bin/sh", "-c"]
    #command: ["while true; do sleep 86400; done"]
volumes:
  zetacored_data:
