# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

## Test locally with `make release-dry-run`

env:
  - CGO_ENABLED=1
  - CC_darwin_arm64=oa64-clang
  - CXX_darwin_arm64=oa64-clang++
  - CC_darwin_amd64=o64-clang
  - CXX_darwin_amd64=o64-clang+
  - CC_linux_arm64=aarch64-linux-gnu-gcc
  - CXX_linux_arm64=aarch64-linux-gnu-g++
  - CC_linux_amd64=x86_64-linux-gnu-gcc
  - CXX_linux_amd64=x86_64-linux-gnu-g++
  - CC_windows_amd64=x86_64-w64-mingw32-gcc
  - CXX_windows_amd64=x86_64-w64-mingw32-g++   
  # - CC_windows_arm64=
  # - CXX_windows_arm64=
  - VERSION = {{ .Version }}
  - COMMIT = {{ .Commit }}
  - BUILDTIME = {{ .Date }}

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go mod tidy

    # you may remove this if you don't need go generate
    # - go generate ./...
    
builds:
  - id: "zetacored-testnet"
    main: ./cmd/zetacored
    binary: zetacored
    env:
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    flags: &default_testnet_flags
      - -tags=TESTNET,pebbledb,ledger,cgo
    ldflags: &default_ldflags
      - -X github.com/cosmos/cosmos-sdk/version.Name=zetacore
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=zetacored
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=zetaclientd
      - -X github.com/cosmos/cosmos-sdk/version.Version=$(VERSION)
      - -X github.com/cosmos/cosmos-sdk/version.Commit=$(COMMIT)
      - -X github.com/zeta-chain/zetacore/common.Name=zetacored
      - -X github.com/zeta-chain/zetacore/common.Version=$(VERSION)
      - -X github.com/zeta-chain/zetacore/common.CommitHash=$(COMMIT)
      - -X github.com/zeta-chain/zetacore/common.BuildTime=$(BUILDTIME)
      - -X github.com/cosmos/cosmos-sdk/types.DBBackend=pebbledb

  - id: "zetaclientd-testnet"
    main: ./cmd/zetaclientd
    binary: zetaclientd
    env:
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    flags: *default_testnet_flags
    ldflags: *default_ldflags

  - id: "zetacored-mock-mainnet"
    main: ./cmd/zetacored
    binary: zetacored
    env:
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    flags: &default_mock_mainnet_flags
      - -tags=MOCK_MAINNET,pebbledb,ledger,cgo
    ldflags: *default_ldflags

  - id: "zetaclientd-mock-mainnet"
    main: ./cmd/zetaclientd
    binary: zetaclientd
    env:
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    flags: *default_mock_mainnet_flags
    ldflags: *default_ldflags

archives:
  # - name_template: "zetachain-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  #   format_overrides:
  #     - goos: windows
  #       format: zip
  #   builds:
  #     - zetacored-testnet-{{ .Os }}-{{ .Arch }} 
  #     - zetaclientd-testnet-{{ .Os }}-{{ .Arch }} 

  - id: testnet
    name_template: "{{ .ProjectName }}-{{ .Version }}-testnet"
    # files:
    #   - LICENSE*
    #   - README*
    #   - CHANGELOG*
    builds: 
      - zetacored-testnet-{{ .Os }}-{{ .Arch }} 
      - zetaclientd-testnet-{{ .Os }}-{{ .Arch }} 

  - id: mock-mainnet
    name_template: "{{ .ProjectName }}-{{ .Version }}-mock-mainnet"
    builds: 
      - zetacored-mock-mainnet-{{ .Os }}-{{ .Arch }} 
      - zetaclientd-mock-mainnet-{{ .Os }}-{{ .Arch }} 
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
snapshot:
  name_template: "{{ .Tag }}-next"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
