version: 0.2

env:
  shell: "/bin/bash"
  git-credential-helper: yes
  
  # variables:
  #   GOENV_DISABLE_GOPATH: "0"
  #   GOVERSION: "go1.17.8"
  #   GOPATH: "/usr/local/go"
  #   GOROOT: "/usr/local/go"
  # exported-variables:
  #   - GOENV_DISABLE_GOPATH
  #   - GOVERSION
  #   - GOPATH
  #   - GOROOT

phases:

  install:
    runtime-versions:
        golang: 1.16
    commands:
      # Install ZetaCore PreReqs - Amazon Linux
      - echo "Install Phase"
      - apt install -y make gcc jq
      - wget https://golang.org/dl/go1.17.8.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.17.8.linux-amd64.tar.gz

  # pre_build:
  #   commands:
  #     - echo "Pre-Build Phase"

  build:
    commands:
      - echo "Build Phase"
      - echo $GOROOT
      - echo $GOPATH
      - make install

  # post_build:
  #   commands:
  #     - echo "Post Build Phase"

artifacts:
  discard-paths: yes
  files:
      - /go/bin/zetaclientd
      - /go/bin/zetacored
      - appspec.yml
      - aws-scripts/*
      - build/zetaclient-start.sh
      - build/zetacored-start.sh