version: 0.2

phases:
  install:
    commands:
      - echo "Install Phase"
      - pwd
      - ls

  build:
    commands:
      - echo "Build Phase"

  post_build:
    commands:
      - echo "Post Build Phase"

artifacts:
  files:
      - '**/*'



#   install:
#     commands:
#       - $(aws ecr get-login --no-include-email)

#   build:
#     commands:
#       - docker build . -t "$REPO_URI"
#       - docker push "$REPO_URI"

#   post_build:
#     commands:
#       - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then echo "Build failed. Skipping."; exit 1; fi
#       - printf '[{"name":"%s","imageUri":"%s"}]' "$NAME" "$REPO_URI" > imagedefinitions.json
#       - cat imagedefinitions.json

# artifacts:
#   files:
#       - imagedefinitions.json
