version: 0.2

env:
  shell: "/bin/bash"
  git-credential-helper: yes
  
  variables:
    GOPATH: "/root/go"
    GOVERSION: "go1.17.8"
  # exported-variables:
  #   - GOPATH


phases:
  install:
    commands:
      # Install ZetaCore PreReqs - Amazon Linux
      - echo "Install Phase"
      - yum install -y make gcc jq
      - wget https://golang.org/dl/go1.17.8.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.17.8.linux-amd64.tar.gz
      - export GOVERSION=go1.17.8
      - export PATH="$PATH:/usr/local/go/bin:/root/go/bin"
      - export GOPATH="/root/go"
      - go version

  # pre_build:
  #   commands:
  #     - echo "Pre-Build Phase"

  build:
    commands:
      - export GOVERSION=go1.17.8
      - export PATH="$PATH:/usr/local/go/bin:/root/go/bin"
      - export GOPATH="/root/go"
      - echo "Build Phase"
      - make install

  # post_build:
  #   commands:
  #     - echo "Post Build Phase"

artifacts:
  discard-paths: yes
  files:
      - /root/go/bin/zetaclientd
      - /root/go/bin/zetacored
      - appspec.yml
      - aws-scripts/*
      - build/zetaclient-start.sh
      - build/zetacored-start.sh