version: "3.9"

services:
  bsc-geth:
    build: 
      context: ./bsc-docker/
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/binance-chain/bsc.git
        GIT_CHECKOUT_REF: master
    image: bsc-geth:docker-local
    platform: linux/amd64
    networks:
      - localnet
networks:
  localnet: 
    external: true
    name: localnet
