version: "3"

# This docker-compose redefine the services:
# - ZetaChain with 2 nodes (zetacore0, zetacore1) using the upgrade option for cosmovisor
# - ZetaChain observer set with 2 clients (zetaclient0, zetaclient1) using the background option
# - Orchestrator with upgrade option

services:
  zetacore0:
    image: zetanode:old

  zetacore1:
    image: zetanode:old

  zetaclient0:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  zetaclient1:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  orchestrator:
    entrypoint: ["/work/start-zetae2e.sh", "local", "upgrade"]
    image: orchestrator

  upgradehost:
    image: zetanode:latest
    container_name: upgradehost
    hostname: upgradehost
    entrypoint: ["/root/start-upgradehost.sh"]
    networks:
      mynetwork:
        ipv4_address: 172.20.0.250
    volumes:
      - ssh:/root/.ssh

  upgradeorchestrator:
    # must run from old node for api compatibility
    image: zetanode:old
    container_name: upgradeorchestrator
    hostname: upgradeorchestrator
    entrypoint: ["/root/start-upgradeorchestrator.sh", "225"]
    networks:
      mynetwork:
        ipv4_address: 172.20.0.251
    depends_on:
      - zetacore0
      - upgradehost
    volumes:
      - ssh:/root/.ssh