version: "3"

# This docker-compose is similar to the docker-compose-upgrade.yml, but it uses a smaller height option for the upgrade (90)
# By using 90, the orchestrator will automatically run setup only for the first e2e test execution.

services:
  zetacore0:
    entrypoint: ["/root/start-zetacored.sh", "2", "upgrade", "90"]
    image: zetanode:old

  zetacore1:
    entrypoint: ["/root/start-zetacored.sh", "2", "upgrade", "90"]
    image: zetanode:old

  zetaclient0:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  zetaclient1:
    entrypoint: ["/root/start-zetaclientd.sh", "background"]
    image: zetanode:old

  orchestrator:
    entrypoint: ["/work/start-zetae2e.sh", "local", "upgrade", "90"]
    image: orchestrator:latest
