version: "3"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:

  zetaclient0:
    image: zetanode:latest
    container_name: zetaclient0
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient0
    networks:
      mynetwork:
        ipv4_address: 172.20.0.21
    entrypoint: /root/start-zetaclientd-p2p-diag.sh


  zetaclient1:
    image: zetanode:latest
    container_name: zetaclient1
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.22
    entrypoint: /root/start-zetaclientd-p2p-diag.sh

  zetaclient2:
    image: zetanode:latest
    container_name: zetaclient2
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.23
    entrypoint: /root/start-zetaclientd-p2p-diag.sh
    environment:
      - MYIP=172.20.0.55


  zetaclient3:
    image: zetanode:latest
    container_name: zetaclient3
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.24
    entrypoint: /root/start-zetaclientd-p2p-diag.sh


