version: "3"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:
  zetacore0:
    image: zetanode:latest
    container_name: zetacore0
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetacore0
    ports:
      - "1317:1317"
      - "9545:8545"
      - "9546:8546"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11
    entrypoint: ["/root/genesis.sh", "4"]


  zetacore1:
    image: zetanode:latest
    container_name: zetacore1
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetacore1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12
    entrypoint: ["/root/genesis.sh", "4"]

  zetacore2:
    image: zetanode:latest
    container_name: zetacore2
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetacore2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.13
    entrypoint: [ "/root/genesis.sh", "4" ]

  zetacore3:
    image: zetanode:latest
    container_name: zetacore3
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetacore3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.14
    entrypoint: [ "/root/genesis.sh", "4" ]

  zetaclient0:
    image: zetanode:latest
    container_name: zetaclient0
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient0
    networks:
      mynetwork:
        ipv4_address: 172.20.0.21
    entrypoint: /root/start-zetaclientd-genesis.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545

  zetaclient1:
    image: zetanode:latest
    container_name: zetaclient1
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.22
    entrypoint: /root/start-zetaclientd-genesis.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545

  zetaclient2:
    image: zetanode:latest
    container_name: zetaclient2
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.23
    entrypoint: /root/start-zetaclientd-genesis.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545

  zetaclient3:
    image: zetanode:latest
    container_name: zetaclient3
    build:
      context: ../../.
      dockerfile: Dockerfile
    hostname: zetaclient3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.24
    entrypoint: /root/start-zetaclientd-genesis.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545

  eth:
    image: ethereum/client-go:v1.10.26
    container_name: eth
    hostname: eth
    ports:
      - "8545:8545"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.100
    entrypoint: [ "geth", "--dev", "--http", "--http.addr", "172.20.0.100", "--http.vhosts", "*", "--http.api", "eth,web3,net", "--http.corsdomain", "https://remix.ethereum.org", "--dev.period", "2" ]

  bitcoin:
    image: ruimarinho/bitcoin-core:22 # version 23 is not working with btcd 0.22.0 due to change in createwallet rpc
    container_name: bitcoin
    hostname: bitcoin
    networks:
      mynetwork:
        ipv4_address: 172.20.0.101
    ports:
      - "18443:18443"
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=172.20.0.0/16
      -rpcbind=0.0.0.0
      -rpcauth=smoketest:63acf9b8dccecce914d85ff8c044b78b$5892f9bbc84f4364e79f0970039f88bdd823f168d4acc76099ab97b14a766a99
      -txindex=1

  orchestrator:
    image: orchestrator:latest
    container_name: orchestrator
    build:
      context: ../../.
      dockerfile: contrib/localnet/orchestrator/Dockerfile
    depends_on:
      - zetacore0
      - eth
    hostname: orchestrator
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    entrypoint: /work/start.sh