version: "3"

# This docker-compose redefine the services:
# - ZetaChain with 4 nodes to test performance
# - ZetaChain observer set with 4 clients to test performance
# - Orchestrator call stress commands

services:
  zetacore0:
    image: zetanode:latest
    container_name: zetacore0
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetacore0
    ports:
      - "1317:1317"
      - "9545:8545"
      - "9546:8546"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11
    entrypoint: ["/root/start-zetacored.sh", "4"]
    environment:
      - HOTKEY_BACKEND=test

  zetacore1:
    image: zetanode:latest
    container_name: zetacore1
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetacore1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12
    entrypoint: ["/root/start-zetacored.sh", "4"]
    environment:
      - HOTKEY_BACKEND=test

  zetacore2:
    image: zetanode:latest
    container_name: zetacore2
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetacore2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.13
    entrypoint: [ "/root/start-zetacored.sh", "4" ]
    environment:
      - HOTKEY_BACKEND=test

  zetacore3:
    image: zetanode:latest
    container_name: zetacore3
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetacore3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.14
    entrypoint: [ "/root/start-zetacored.sh", "4" ]
    environment:
      - HOTKEY_BACKEND=test

  zetaclient0:
    image: zetanode:latest
    container_name: zetaclient0
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetaclient0
    networks:
      mynetwork:
        ipv4_address: 172.20.0.21
    ports:
      - "8123:8123"
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=test

  zetaclient1:
    image: zetanode:latest
    container_name: zetaclient1
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetaclient1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.22
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=test

  zetaclient2:
    image: zetanode:latest
    container_name: zetaclient2
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetaclient2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.23
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=test

  zetaclient3:
    image: zetanode:latest
    container_name: zetaclient3
    build:
      context: ../../.
      dockerfile: Dockerfile-localnet
    hostname: zetaclient3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.24
    entrypoint: /root/start-zetaclientd.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545
      - HOTKEY_BACKEND=test

  orchestrator:
    image: orchestrator:latest
    container_name: orchestrator
    build:
      context: ../../.
      dockerfile: contrib/localnet/orchestrator/Dockerfile.fastbuild
    depends_on:
      - zetacore0
      - eth
    hostname: orchestrator
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    entrypoint: ["/work/start.sh", "stress"]