name: 'Upload Deployment Files To S3'
description: 'Uploads Files To S3'
inputs:
  bucket-name:  
    description: 'S3 Bucket Name'
    required: true
  release-name:  
    description: 'Name of GitHub tag or release (Usually $GITHUB_REF_NAME)'
    required: true
  git-sha:  
    description: 'SHA hash of GitHub commit'
    required: true
  files:  
    description: "Newline-delimited list of asset files to upload"
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload Files
      run: |
        echo "Running Upload-To-S3 Action"
        RELEASE_NAME=${{ inputs.release-name }}
        GIT_SHA=${{ inputs.git-sha }}

        if [[ "$RELEASE_NAME" == "develop" ]]; then
          echo "Use GITHUB_SHA instead of develop branch name"
          S3_PREFIX=$GIT_SHA
        else
           S3_PREFIX=$RELEASE_NAME
        fi

        while IFS= read -r FILEPATH; do
            FILENAME=$(echo "$FILEPATH" | cut -d / -f2)
            aws s3 cp "$FILEPATH" s3://"$S3_BUCKET_PATH"/"$RELEASE_NAME"/"$FILENAME"
        done <<< $(echo "${{ inputs.files }}" | awk NF)
      shell: bash   

