name: 'Build Binaries'
description: 'Builds ZetaChain Binaries'
inputs:
  run-tests:  
    description: 'Run Build Tests (true/false)'
    required: false
    default: "false"
  go-version:  
    description: 'Optional - Install a specific verion of Go'
    required: false
    default: ''
  ENVIRONMENT_NAME:  
    description: 'Environment Name'
    required: true
    default: "STAGING"

runs:
  using: "composite"
  steps:
    - name: Set Up Go 
      # Optionally install a specific version of Go
      # Only use if go has not been installed in a previous step of the calling workflow
      if : ${{ inputs.go-version != '' }} 
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}  
        cache: true
        cache-dependency-path: go.mod
          
    - name: build zetacored and zetaclientd
      shell: bash
      run: |
        make install
        cp "$HOME"/go/bin/* ./

    - name: Run Build tests
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: |
        echo "Running Build Tests"
        make test

    - name: Cosmovisor
      shell: bash
      run: |
        go get github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/cosmovisor@zetavisor-v0.1.2
        go install github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/cosmovisor@zetavisor-v0.1.2
        cp "$HOME"/go/bin/cosmovisor ./cosmovisor

    - run: echo "Completed Build Action"
      shell: bash


