name: 'Create Cosmovisor Release Package'
description: 'Does cosmovisor stuff '
inputs:
  # RELEASE_NAME:  
  #   description: 'Name of GitHub tag or release (Usually $GITHUB_REF_NAME)'
  #   required: true
  S3_BUCKET_NAME:  
    description: 'S3 Bucket Name'
    required: true
  TAKE_SNAPSHOTS:  
    description: 'Take Snapshots of Node Storage before update'
    required: false
    default: "true"
  UPDATE_INDEXER:  
    description: 'Update the Indexer Node'
    required: false
    default: "false"
  # ENVIRONMENT_NAME:  
  #   description: 'Environment Name'
  #   required: true
  #   default: "STAGING"

runs:
  using: "composite"
  steps:
    - name: Set ENV Variables
      run: |
        echo Running ZetaChain Build Action
        echo "::set-env name=INPUT_RUN_TESTS::${{ inputs.run-tests }}"
        echo "::set-env name=INPUT_BUILD_INDEXER::${{ inputs.build-indexer }}"
        echo "::set-env name=INPUT_ENVIRONMENT_NAME::${{ inputs.ENVIRONMENT_NAME }}"
      shell: bash
    - name: Set ENV Variables
    - name: Set ENV Variables

      


