version: "3"

services:
  ganache-eth:
    container_name: ganache-eth
    image:  trufflesuite/ganache:latest
    environment:
      - NODE_OPTIONS=--max_old_space_size=4098
    volumes:
      - ./storage/:/storage
    ports:
        - "8100:8545" # RPC Endpoint
    networks:
      localnet:
    command: > 
      --logging.verbose=false 
      --logging.debug=false 
      --logging.debug=true 
      --wallet.totalAccounts=2 -u=0 -u=1 
      --wallet.defaultBalance 100000000000000000000 
      --chain.chainId 5 
      --chain.networkId 5 
      --chain.vmErrorsOnRPCResponse true 
      --chain.asyncRequestProcessing true 
      --miner.blockTime 12 

#  ganache-eth-2:
#     container_name: ganache-eth-2
#     # env_file:
#     #   - .env
#     image:  trufflesuite/ganache:latest
#     environment:
#       - NODE_OPTIONS=--max_old_space_size=4098
#     volumes:
#       - ./storage/:/storage
#     ports:
#         - "8110:8545" # RPC Endpoint
#     networks:
#       localnet:
#     command: > 
#       --logging.verbose=false 
#       --logging.debug=false 
#       --logging.debug=true 
#       --wallet.totalAccounts=2 -u=0 -u=1 
#       --wallet.defaultBalance 100000000000000000000 
#       --chain.chainId 3 
#       --chain.networkId 3
#       --chain.vmErrorsOnRPCResponse true 
#       --chain.asyncRequestProcessing true 
#       --miner.blockTime 12 
#       --database.dbPath /storage/fork.eth-2.db

  ganache-bsc:
    container_name: ganache-bsc
    image:  trufflesuite/ganache:latest
    environment:
      - NODE_OPTIONS=--max_old_space_size=4098
    volumes:
      - ./storage/:/storage
    ports:
        - "8120:8545" # RPC Endpoint
    networks:
      localnet:
    command: > 
      --logging.verbose=false 
      --logging.debug=false 
      --logging.debug=true 
      --wallet.totalAccounts=2 -u=0 -u=1 
      --wallet.defaultBalance 100000000000000000000 
      --chain.chainId 97 
      --chain.networkId 97
      --chain.vmErrorsOnRPCResponse true 
      --chain.asyncRequestProcessing true 
      --miner.blockTime 2 



  ganache-polygon:
    container_name: ganache-polygon
    image:  trufflesuite/ganache:latest
    environment:
      - NODE_OPTIONS=--max_old_space_size=4098
    volumes:
      - ./storage/:/storage
    ports:
        - "8140:8545" # RPC Endpoint
    networks:
      localnet:
    command: > 
      --logging.verbose=false 
      --logging.debug=false 
      --logging.debug=true 
      --wallet.totalAccounts=2 -u=0 -u=1 
      --wallet.defaultBalance 100000000000000000000 
      --chain.chainId 80001 
      --chain.networkId 80001
      --chain.vmErrorsOnRPCResponse true 
      --chain.asyncRequestProcessing true 
      --miner.blockTime 2 

networks:
  localnet: 
    external: true
    name: localnet
