name: Development - Build & Deploy

## TODO 
  # Remove static IAM creds and use short lived via Role Assumption
  # Add Testing Stage
  # Add Rollback Stage
  # Setup CosmoVisor Proposal action


on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release to deploy'
        required: true
      upgrade_block_height:
        description: 'What block height to upgrade at'
        required: true
      environment:
        description: 'Environment to deploy this release to'
        type: environment
        required: true


env:
  S3_BUCKET_NAME: "zetachain-deployment-files"
  AWS_REGION: "us-east-1"

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.8
        with:
          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      ## GEt release files from S3 or get the URL

      # NOT READY YET
      # - name: Cosmovisor Upgrade Proposal and Vote
      #   uses:  ./.github/actions/cosmovisor-upgrade
      #   with:
      #     RELEASE_NAME: "$(echo ${{ github.ref_name }} | tr '//' '-')"
      #     VERSION: "0.0.1"
      #     # DESCRIPTION: "description"
      #     S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
      #     # CHECKSUM_ZETACORED: ""
      #     # CHECKSUM_ZETACLIENTD: ""
      #     CHAIN_ID: "athens-1"
      #     API_ENDPOINT: "https://api.staging.zetachain.com"

