name: Deploy ZetaChain Update via Cosmovisor
on:
  workflow_dispatch:
    inputs:
      UPGRADE_NAME:
        description: 'Name of the upgrade (0.0.1)'
        type: string
        required: true
      UPGRADE_BLOCK_HEIGHT:
        description: 'What block height to upgrade at - If Blank, will upgrade in 150 blocks'
        type: string
        required: false
      ENVIRONMENT:
        description: 'What Environment to deploy into (athens2, development)'
        type: environment
        required: true

env:
  S3_BUCKET_NAME: "zetachain-deployment-files"
  AWS_REGION: "us-east-1"

jobs:
  deploy-cosmovisor-upgrade:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.8
        with:
          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Chain ID Automatically based on Environment
        run: |
          if [ ${{ github.event.inputs.ENVIRONMENT }} == "development" ]; then
            echo "using development chain id: develop_101-1"
            echo "CHAIN_ID=develop_101-1" >> $GITHUB_ENV
          elif [ ${{ github.event.inputs.ENVIRONMENT }} == "athens2" ]; then
            echo "using athens2 chain id"
            echo "CHAIN_ID=athens_7001-1" >> $GITHUB_ENV
          fi

      - name: Get Checksum
        run: |
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetacored ./ || exit 1
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetaclientd ./ || exit 1
          ZETACORED_CHECKSUM=$(shasum -b -a 256 zetacored | cut -d ' ' -f 1)
          ZETACLIENTD_CHECKSUM=$(shasum -b -a 256 zetaclientd | cut -d ' ' -f 1)
          echo "ZETACORED_CHECKSUM=$ZETACORED_CHECKSUM" >> $GITHUB_ENV
          echo "ZETACLIENTD_CHECKSUM=$ZETACLIENTD_CHECKSUM" >> $GITHUB_ENV

      # Approval needed to deploy to environments other than development
      # - uses: trstringer/manual-approval@v1
      #   if : ${{ github.event.inputs.ENVIRONMENT != 'development' }}
      #   with:
      #     secret: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
      #     approvers: charliemc0, brewmaster012, kingpinXD, afzeta, chriskzeta, lucas-janon
      #     minimum-approvals: 1
      #     issue-title: "Protocol Upgrade ${{ github.ref_name }} Env: ${{ github.event.inputs.ENVIRONMENT }}"
      #     exclude-workflow-initiator-as-approver: false

      - name: Test Inputs
        if: ${{ env.ACT }}
        run: |
          echo  ${{ github.ref_name }}
          echo  ${{ github.event.inputs.ENVIRONMENT }}
          echo  ${{ env.CHAIN_ID }}
          echo  ${{ github.event.inputs.UPGRADE_BLOCK_HEIGHT }}
          echo  ${{ env.ZETACORED_CHECKSUM }}
          echo  ${{ env.ZETACLIENTD_CHECKSUM }}

      - name: Cosmovisor Upgrade Proposal and Vote
        uses:  ./.github/actions/cosmovisor-upgrade
        with:
          UPGRADE_NAME: ${{ github.event.inputs.UPGRADE_NAME }}
          CHAIN_ID: ${{ env.CHAIN_ID }}
          DESCRIPTION: "Description Goes Here"
          ZETACORED_CHECKSUM: ${{ env.ZETACORED_CHECKSUM }}
          ZETACORED_URL: "https://${{ env.S3_BUCKET_NAME }}.s3.amazonaws.com/${{ github.ref_name }}/zetacored"
          ZETACLIENTD_CHECKSUM: ${{ env.ZETACLIENTD_CHECKSUM }}
          ZETACLIENTD_URL: "https://${{ env.S3_BUCKET_NAME }}.s3.amazonaws.com/${{ github.ref_name }}/zetaclientd"
          API_ENDPOINT: "https://api.${{ github.event.inputs.ENVIRONMENT }}.zetachain.com"
          UPGRADE_BLOCK_HEIGHT: ${{ github.event.inputs.UPGRADE_BLOCK_HEIGHT }}

