name: "TESTING:ADVANCED:E2E"

on:
  workflow_dispatch:
    inputs:
      e2e-admin-tests:
        type: boolean
        required: false
        default: false
      e2e-upgrade-test:
        type: boolean
        required: false
        default: false
      e2e-performance-test:
        type: boolean
        required: false
        default: false
      e2e-upgrade-test-light:
        type: boolean
        required: false
        default: false

jobs:
  e2e-admin-tests:
    if: ${{ github.event.inputs.e2e-admin-tests == 'true' }}
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 120
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Execute e2e-admin-tests
        shell: bash
        run: |
          make start-e2e-admin-test

          # Loop indefinitely until no containers are running
          while true; do
              # Get the IDs of all running containers
              running_containers=$(docker ps -q)
              
              # If no containers are running, exit the loop
              if [ -z "$running_containers" ]; then
                  echo "No running containers. Exiting..."
                  break
              fi
          
              # For each running container, check if it has stopped and log its output
              for container_id in $running_containers; do
                  # Check if the specific container is still running
                  if [ -z "$(docker ps -q | grep $container_id)" ]; then
                      # Since the container has stopped, fetch and display its logs
                      echo "Container $container_id has stopped. Fetching logs:"
                      docker logs $container_id
                      echo "-----------------------------------"
                  fi
              done
              
              # Show the current state of running containers
              echo "Current running containers:"
              docker ps
              
              # Wait a bit before checking again
              sleep 5
          done
          
          echo "All containers have stopped."
          
  e2e-upgrade-test:
    if: ${{ github.event.inputs.e2e-upgrade-test == 'true' }}
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 120
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Execute upgrade-test
        shell: bash
        run: |
          make start-upgrade-test

  e2e-upgrade-test-light:
    if: ${{ github.event.inputs.e2e-upgrade-test-light == 'true' }}
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 120
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Execute upgrade-test-light
        shell: bash
        run: |
          make start-upgrade-test-light

  e2e-performance-test:
    if: ${{ github.event.inputs.e2e-performance-test == 'true' }}
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 120
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Execute Performance Tests
        shell: bash
        run: |
          make start-e2e-performance-test
