name: Generate Go and OpenAPI from Protobuf
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1

      - name: Install protoc plugins
        run: |
          go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@latest
          go install github.com/regen-network/cosmos-proto/protoc-gen-gocosmos
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Add protoc plugins to PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate Go and OpenAPI
        run: make proto

      - name: Check for changes
        run: |
          git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol
