name: Generate Go and OpenAPI from Protobuf
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Go packages
        run: |
          make proto

      - name: Check for changes
        run: |
          git diff --exit-code
