name: Generated Files are Updated
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1

      - name: Add protoc plugins to PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate Go code from proto files
        run: make proto

      - name: Generate OpenAPI
        run: make openapi

      - name: Generate Module Documentation
        run: make specs

      - name: Check for changes
        run: |
          if git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol; then
            echo "Generated Go files are up-to-date."
          else
            echo "::error::Generated files are not up-to-date. Please run 'make generated' locally and commit any changes."
            exit 1
          fi
