name: Go-Releaser

on:
  push:
    tags:

jobs:
  go-releaser:
    runs-on: buildjet-4vcpu-ubuntu-2004
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Publish Release Files
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
        run: |
          touch .release-env
          make release