name: Gosec
on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

env: 
  GOPRIVATE: "github.com/zeta-chain/*"
  
jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.8
        with:
          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
          