name: Linter

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

env: 
  GOPRIVATE: github.com/zeta-chain/*
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        
      - name: setup-git-credentials
        uses: de-vri-es/setup-git-credentials@v2.0.8
        with:
          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.47
