name: Deploy to EC2

on:
  push:
    branches: [ athens-aws]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make install


    - name: Install Octopus CLI 🐙
      uses: OctopusDeploy/install-octopus-cli-action@v1
      with:
        version: latest

    - name: Push a package to Octopus Deploy 🐙
      uses: OctopusDeploy/push-package-action@v1
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        packages: '/home/runner/go/bin/zetacored,/home/runner/go/bin/zetaclient'
        server: ${{ secrets.OCTOPUS_SERVER }}

