name: Test-Cross-Compile-Binary-On-Runner

on:
  workflow_dispatch:
    inputs:
      binary_link:
        description: 'The link for the binary you want to test.'
        required: false
        default: 'https://github.com/zeta-chain/node/releases/download/v10.1.2/zetacored_testnet-linux-amd64'


jobs:
  check_binary:
    runs-on: ['zeta-runners-athens3']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download and test.
        run: |
          echo "Download test binary"
          wget -q ${{ github.event.inputs.binary_link }} -O ./zetacored
          
          echo "Change permissions"
          sudo chmod a+x ./zetacored
          
          echo "Zetacored Version"
          ./zetacored version
          
          echo "Print OS Version"
          lsb_release -d
